### ISSUE TITLE
Is it possible to add external anten for Wifi  ?

### ISSUE THREAD

**Issue by David-2D3FE9** [Xinyuan-LilyGO/LilyGo-T-Relay#2]
Hello first of all, thank you for the versatily and the quality of your products.   
I am realy enjoy to discover your T-Relay board and I am wondering if it is possible to add an external antenna for the wifi.  

On the product picture it seem to have pads near ESP32,   
Is it for soldering an SMA connector for external Wifi Antenna ?   

![image](https://user-images.githubusercontent.com/64800039/140622812-aefd395f-a2c9-497d-9586-3da81838d4a1.png)

Thanks in advance for your response

**Comment by LilyGO** [comment]
Hello. Modules have onboard antennas. If external antennas are used, jump resistors and weld antenna seats are required.

**Comment by David-2D3FE9** [comment]
Thanks for your response.
My delivery isdelayed so I will see that in January :-)
