### ISSUE TITLE
Testing T-Relay W5500 Shield - discovery working but no LEDs (LinkOFF)

### ISSUE THREAD

**Issue by linkedupbits** [Xinyuan-LilyGO/LilyGo-T-Relay#25]
I have the T-4 relay and the T-Relay W5500 Shield and I am trying to get the sample working.

The W5500 initializes (serial monitor prints "Ethernet W5100 Discovery !") but 
``` c++
Ethernet.linkStatus()
```
always returns LinkOFF, and the LEDs on the RJ45 socket do not light up.

I understand I should be able to test the LEDs simply by plugging in a live network cable and supplying 3.3v and Gnd to the W5500 (without having the T-relay connected) - just for testing.

Which of the header pins (other than the SPI) are used on the T-Relay W5500 Shield and are connected ?
 
There should be 3 x GND and two 3v3 as per the pinout, and the SPI communication appears to be working based on successful discovery.

Thanks in advance

**Comment by Llgok** [comment]
> I have the T-4 relay and the T-Relay W5500 Shield and I am trying to get the sample working.
> 
> The W5500 initializes (serial monitor prints "Ethernet W5100 Discovery !") but
> 
> ```c++
> Ethernet.linkStatus()
> ```
> 
> always returns LinkOFF, and the LEDs on the RJ45 socket do not light up.
> 
> I understand I should be able to test the LEDs simply by plugging in a live network cable and supplying 3.3v and Gnd to the W5500 (without having the T-relay connected) - just for testing.
> 
> Which of the header pins (other than the SPI) are used on the T-Relay W5500 Shield and are connected ?
> 
> There should be 3 x GND and two 3v3 as per the pinout, and the SPI communication appears to be working based on successful discovery.
> 
> Thanks in advance

Your Ethernet cable may not be properly connected.

After the W5500 device is correctly recognized, insert the router-connected Ethernet cable, and you will see "Link status: ON" on the serial port, indicating that the connection is normal. (There are 3 states: "Link status: ON" indicates a normal connection, "Link status: OFF" indicates that the Ethernet port is not plugged in, and "Link status: Unknown" indicates an unknown connection, which is a hardware error and the W5500 and Ethernet port cannot communicate.)
