### ISSUE TITLE
Internal PCF8563 not incrementing with T-Relay S3 [H629]

### ISSUE THREAD

**Issue by Olli69** [Xinyuan-LilyGO/LilyGo-T-Relay#26]
Hi, 
I tested internal PCF8563 rtc with the sample program RTC_PCF8563_TimeSynchronization. It got updates from ntp-server and set date/time to the rtc, but the rtc was not incrementing. For example just after ntp update loop() printed out 
```
Hardware clock :Wednesday, January 31 2024 17:25:17
System   clock :Wednesday, January 31 2024 17:25:17
````
but 10 seconds later:
```

Hardware clock :Wednesday, January 31 2024 17:25:17
System   clock :Wednesday, January 31 2024 17:25:27
```

I had the same problem with Adafruit library as well as https://github.com/Makuna/Rtc library. Could it be a hardware problem? I just got the board from LilyGo (order 13992).

**Comment by lewisxhe** [comment]
Can you use I2C scan to test whether PCF8563 is online?
Normally, as long as the PCF8563 is powered on, the time will accumulate.

**Comment by Olli69** [comment]
> Can you use I2C scan to test whether PCF8563 is online? Normally, as long as the PCF8563 is powered on, the time will accumulate.

It has a fresh CR-1220 battery (does it save the static time but not accumulate?) . Also response from i2c scan (`WIRE.begin(16,17);`): `I2C device found at address 0x51  !`

**Comment by lewisxhe** [comment]
Then I may suspect that the RTC crystal is not working properly. Is it possible for you to measure the clock waveform of 32.768khz?

**Comment by Olli69** [comment]
I do have an oscilloscope, but not very professional with it. If you could send  a pic of pins to measure, I could try.

**Comment by lewisxhe** [comment]
I will send it to you tomorrow and add instructions

**Comment by lewisxhe** [comment]
![image](https://github.com/Xinyuan-LilyGO/LilyGo-T-Relay/assets/22990954/ae29b093-1367-4495-929b-198baad14167)

Check these two pins, adjust the oscilloscope probe to the 10X gear, then adjust the period to 10us and the voltage to 50mV. If your oscilloscope supports period measurement, you can open the period measurement option and observe whether there is a 32.768khz waveform output.

**Comment by Olli69** [comment]
I got quite nice sine waves from pin 1 and pin 2.  But are the voltage levels correct for PCF8563 to operate, OSCI between 356mV-828mV? I measured VDD voltage levels from PIN 8: 2.88V-3.12V. 

![DS1Z_PCF8563_PIN1_OSCI](https://github.com/Xinyuan-LilyGO/LilyGo-T-Relay/assets/1752838/d5b0da4b-0e74-42f7-8e34-08bd0207d7f8)
![DS1Z_PCF8563_PIN2_OSCO](https://github.com/Xinyuan-LilyGO/LilyGo-T-Relay/assets/1752838/9f74dd31-cf10-455c-879a-3d7eb8d253ff)

**Comment by lewisxhe** [comment]
There seems to be no problem. The crystal is already oscillating. You can try my test file to see if it accumulates every one second.

There seems to be no problem. The crystal is already oscillating. You can try my test file to see if it accumulates every one second.

[RTC_Firmware.zip](https://github.com/Xinyuan-LilyGO/LilyGo-T-Relay/files/14121926/RTC_Firmware.zip)

How to flash firmware , you can see here, the method is the same, the writing address is 0x0

https://github.com/Xinyuan-LilyGO/LilyGo-AMOLED-Series/blob/master/firmware/README.MD#2%EF%B8%8F%E2%83%A3how-to-flash-

**Comment by Olli69** [comment]
Thanks for additional diagnostics. I flashed your test file and it does not seem to accumulate.
```
Hardware clock :Monday, January 01 2024 00:00:00
Hardware clock :Monday, January 01 2024 00:00:00
Hardware clock :Monday, January 01 2024 00:00:00
Hardware clock :Monday, January 01 2024 00:00:00
Hardware clock :Monday, January 01 2024 00:00:00
Hardware clock :Monday, January 01 2024 00:00:00
Hardware clock :Monday, January 01 2024 00:00:00
```

**Comment by lewisxhe** [comment]
@Olli69 Sorry for confusing you
At present, it seems from all aspects that the PCF8563 chip may be damaged, causing it to not work properly. Please contact customer service for after-sales service.

**Comment by Olli69** [comment]
@lewisxhe , no problem! Thank you for prompt responses with diagnostics. So good that we got this far so quickly. I have contacted your sales and asked for a replacement board.

**Comment by lewisxhe** [comment]
You're welcome. If you don't have any other questions, please close it.
