### ISSUE TITLE
LilyGo-T-Relay w5500: Which hardware SPI Pins? 

### ISSUE THREAD

**Issue by JFLSeoul** [Xinyuan-LilyGO/LilyGo-T-Relay#28]
Hello I just bought LilyGo-T-Relay 4 way and trying to add ethernet with a w5500 module (a standard one, not the LilyGo one) What are the correct Hardware SPI pins? On the homepage the picture shows: PIN_W5500_CLK IO22, PIN_W5500_MOSI IO26, PIN_W5500_MISO IO13, PIN_W5500_CS IO27, are those the correct pins ? I have tested the same shield with another esp32 without any problem, but having problems to get this running on the LilyGo...Thanks Joop

**Comment by Llgok** [comment]
> Hello I just bought LilyGo-T-Relay 4 way and trying to add ethernet with a w5500 module (a standard one, not the LilyGo one) What are the correct Hardware SPI pins? On the homepage the picture shows: PIN_W5500_CLK IO22, PIN_W5500_MOSI IO26, PIN_W5500_MISO IO13, PIN_W5500_CS IO27, are those the correct pins ? I have tested the same shield with another esp32 without any problem, but having problems to get this running on the LilyGo...Thanks Joop

Hello,

The pin configuration for the W5500 module on the LilyGo-T-Relay-4 version is:
#define PIN_W5500_CLK 22
#define PIN_W5500_MISO 13 // LilyGo-T-Relay-4
#define PIN_W5500_MOSI 26
#define PIN_W5500_CS 27
#define PIN_W5500_RESET 23
#define PIN_W5500_INT 36

The pin configuration for the W5500 module on the LilyGo-T-Relay-8 version is:
#define PIN_W5500_CLK 22
#define PIN_W5500_MISO 34 // LilyGo-T-Relay-8
#define PIN_W5500_MOSI 26
#define PIN_W5500_CS 27
#define PIN_W5500_RESET 23
#define PIN_W5500_INT 36
