### ISSUE TITLE
What is the maximum current rating for the relay ?

### ISSUE THREAD

**Issue by X-Ryl669** [Xinyuan-LilyGO/LilyGo-T-Relay#3]
I see you have mounted 10A relay. Are the screw terminal block and PCB trace matched for 10A ?

**Comment by LilyGO** [comment]
Yes. You can refer to the parameters of the relay

**Comment by X-Ryl669** [comment]
The trace width seems like they are 3.8mm on the bottom layer but 7.6mm is required to pass 10A on a 1oz PCB (unless there is a trace going under the relay themselves on the top layer too).
Is the PCB copper layer made of 2oz ? 
Or is there a trace on the relay pin on the top layer too ?

**Comment by LilyGO** [comment]
Yes, it is not recommended to exceed the limit value.

**Comment by SublimeMudTime** [comment]
It almost looks like there are traces for the relay on the top and bottom when examining my board. And 2 X 3.8 = 7.6 so it seems ok...

**Comment by X-Ryl669** [comment]
Thanks! I've received mine recently and indeed, there are traces on both side so it's ok.
