### ISSUE TITLE
LilyGo T-Relay(6) S3 - pin assigments in documentation doesnt match schematic/reallity

### ISSUE THREAD

**Issue by LordRafa** [Xinyuan-LilyGO/LilyGo-T-Relay#30]
The pin assignments shown in [LilyGo T Relay S3](https://github.com/Xinyuan-LilyGO/LilyGo-T-Relay/blob/main/docs/RELAY_ESP32S3.MD) documentation doesn't match the [schematics](https://github.com/Xinyuan-LilyGO/LilyGo-T-Relay/blob/main/Schematic/T_Relay6_ESP32S3.pdf).

I think that these are the right ones:
static const uint8_t TX = 43;
static const uint8_t RX = 44;

static const uint8_t SDA = 16;
static const uint8_t SCL = 17;

// Temperature Sensor
static const uint8_t DSDATA = 21; // Not Connected

// RTC
static const uint8_t RTC_CLK32 = 15; // Not Connected
static const uint8_t RTC_INT = 18;

// HT74HC595ARZ

static const uint8_t SHIFT_REG_CLK   = 5
static const uint8_t SHIFT_REG_LATCH = 6
static const uint8_t SHIFT_REG_DATA  = 7

**Comment by lewisxhe** [comment]
Thank you. It seems that the document was not changed in time after changing the GPIO. It has been corrected now.
