### ISSUE TITLE
info about PS RAM

### ISSUE THREAD

**Issue by freiregtr** [Xinyuan-LilyGO/LilyGo-T-Relay#32]
hello there!

I have doubts regarding the true capacity of the PS RAM of the device, since when I started reading the ESP32 memories, I found that the reading gave me 4MB, but according to the description of the device at the time of purchase it indicates that it comes with 8MB

![imagen](https://github.com/Xinyuan-LilyGO/LilyGo-T-Relay/assets/34633333/82fcaf43-d651-4d33-9511-29176a3ada9a)

![imagen](https://github.com/Xinyuan-LilyGO/LilyGo-T-Relay/assets/34633333/ac2ca7f2-d859-407e-ac1b-39b44de42526)

Could you help me understand why I read less PS RAM than what is specified in the product? thanks

**Comment by lewisxhe** [comment]
https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/himem.html
![image](https://github.com/Xinyuan-LilyGO/LilyGo-T-Relay/assets/22990954/112450a9-ff18-4066-8352-909441f78ad7)
