### ISSUE TITLE
What is the correct GPIO pin for K4 relay

### ISSUE THREAD

**Issue by tichaonax** [Xinyuan-LilyGO/LilyGo-T-Relay#4]
The documentation for K4 relay says GPIO 05 and others GPIO 15.
I have tried both of them and none work to toggle the relay. The other GPIO 18, 19 and 21 work

**Comment by tichaonax** [comment]
I verified it is GPIO 05, there is documentation out there that refers to it as GPIO 15

**Comment by LilyGO** [comment]
Hello, K4 is GPIO5, [refer to](https://github.com/Xinyuan-LilyGO/LilyGo-T-Relay#pinout) .  In which document did you see GPIO15?
