### ISSUE TITLE
password startAP

### ISSUE THREAD

**Issue by maestrone** [Xinyuan-LilyGO/LilyGo-T-Relay#42]
please the password of the factory build AP whit the SSID: LilyGo-Relay

thx

**Comment by lewisxhe** [comment]
By default, the ap is open and has no password.

**Comment by maestrone** [comment]
thanks for the fast replay

mmhh, on Ios und MacOS is one required...
![IMG_2258](https://github.com/user-attachments/assets/59db17d8-9bdc-4000-927f-4483a349cad7)

**Comment by lewisxhe** [comment]
You try 12345678
