### ISSUE TITLE
How to upload with USBtoSerial CH340

### ISSUE THREAD

**Issue by garudaonekh** [Xinyuan-LilyGO/LilyGo-T-Relay#8]
Hi,
is there a way to upload via USB-Serial CH340 without using the usb tongle? I forget to buy it with this relay

**Comment by LilyGO** [comment]
No USB connector. You can only download by cable.

**Comment by garudaonekh** [comment]
Yes, how to connect the PIN for RX/TX?

**Comment by LilyGO** [comment]
![1](https://user-images.githubusercontent.com/31160602/153787682-d2d83422-5de3-497e-a7da-1abd7490d344.png)

**Comment by Jason2866** [comment]
Great board design decision. Seems there was nowhere place left to make rx, tx and gpio0 accessible. O wait users could use easily there own usb-serial adapter. How could i forgot this.
